- name: Jira
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Update Minimal
      command: 'yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical --setopt=tsflags=nodocs --disablerepo "*" --enablerepo rhel-7-server-rpms,rhel7-server-optional-rpms'

    - name: Install Packages
      yum:
        name: "{{ item }}"
        state: present
        disablerepo: "*"
        enablerepo: "rhel-7-server-rpms,rhel-7-server-optional-rpms,rhel-7-server-ose-3.3-rpms"
      with_items:
        - wget
        - nss_wrapper
        - gettext
        - golang-github-cpuguy83-go-md2man

    - name: Create man page
      command: go-md2man -in /tmp/help.md -out /help.1
      register: manpage

    - name: Remove help.md file
      file:
        dest: /tmp/help.md
        state: absent
      when: "{{ manpage|success }}"

    - name: Remove go-md2man package
      yum:
        pkg: "{{ item }}"
        state: absent
      with_items:
        - golang-github-cpuguy83-go-md2man

    - name: Download MySQL Java Connector
      get_url:
        url: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.38.tar.gz
        dest: /tmp/mysql.tar.gz

    - name: Extract MySQL Java Connector
      command: tar -xf /tmp/mysql.tar.gz --directory /tmp --strip-components=1 --no-same-owner "mysql-connector-java-5.1.38/mysql-connector-java-5.1.38-bin.jar"

    - name: Download Jira
      get_url:
        url: "https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-core-{{ application_version }}-x64.bin"
        dest: /tmp/jira.bin
        mode: 0755

    - name: Create Directories
      file:
        dest: "{{ item }}"
        state: directory
        recurse: yes
      with_items:
        - "{{ application_install }}/lib"
        - "{{ application_install }}/caches/indexes"

    - name: Run Installer
      command: /tmp/jira.bin -q -varfile /tmp/response.varfile

    - name: Copy MySQL Java Connectory
      copy:
        src: /tmp/mysql-connector-java-5.1.38-bin.jar
        dest: "{{ application_install }}/lib"

    - name: Remove MySQL Connector from /tmp
      file:
        dest: /tmp/mysql-connector-java-5.1.38-bin.jar
        state: absent

    - name: Remove Jira binary
      file:
        dest: /tmp/jira.bin
        state: absent

    - name: Fix Permissions
      file:
        dest: "{{ item }}"
        state: directory
        owner: jira
        group: root
        mode: 0775
        recurse: yes
      with_items:
         - "{{ application_install }}/conf"
         - "{{ application_install }}/logs"
         - "{{ application_install }}/temp"
         - "{{ application_install }}/work"
