apiVersion: v1
kind: Template
metadata:
  name: starter-nsswrapper
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: starter-nsswrapper
    name: starter-nsswrapper
  spec:
    tags:
    - name: "starter-nsswrapper"
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "starter-nsswrapper"
  spec:
    source:
      git:
        uri: https://github.com/RHsyseng/container-rhel-examples
      contextDir: "starter-nsswrapper"
    strategy: 
      type: "Docker"
    output:
      to:
        kind: "ImageStreamTag"
        name: "starter-nsswrapper:latest"
    triggers:
    - generic:
        secret: b725254e6534fd70
      type: Generic
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 7
    labels:
      app: starter-nsswrapper
    name: starter-nsswrapper
  spec:
    replicas: 1
    selector:
      app: starter-nsswrapper
      deploymentconfig: starter-nsswrapper
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: starter-nsswrapper
          deploymentconfig: starter-nsswrapper
      spec:
        containers:
        - env:
          - name: HOME
            value: /opt/app-root
          image: 172.30.93.229:5000/starter-nsswrapper/starter-nsswrapper@sha256:f5f80e5c582c0e5ed010a9057ce5c6458c31f4e28c652d0e1f9397cd543c2b31
          imagePullPolicy: Always
          name: starter-nsswrapper
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - starter-nsswrapper
        from:
          kind: ImageStreamTag
          name: starter-nsswrapper:latest
          namespace: starter-nsswrapper
      type: ImageChange