#!/bin/sh
set -x
usermod -u ${USER_UID} -g 0 ${USER_NAME} 
chown -R ${USER_UID}:0 ${APP_ROOT} ${APP_HOME}
chmod -R g+rw ${APP_ROOT} ${APP_HOME} /etc/passwd
find ${APP_ROOT} -type d -exec chmod g+x {} +
find ${APP_HOME} -type d -exec chmod g+x {} +
